### ISSUE TITLE
Only update eNom domains

### ISSUE THREAD

**Issue by oznorts** [ducohosting/whmcs-enom-updater#15]
This module should only update/get pricing for domains that are auto registered with eNom.  Some domains are cheaper through Namecheap, for example, and I sell through them for those (especially when Namecheap has domains on sale).  I don't want this module to override the pricing for those TLDs.

Great module, though!  Been looking for this for a long time!

**Comment by cascer1** [comment]
Thanks for the feedback, that's indeed a missing feature right now!

**Comment by cascer1** [comment]
I released [2.1.0 Alpha 1](https://github.com/ducohosting/whmcs-enom-updater/releases/tag/v2.1.0-alpha1) with this feature, check it out!

It currently honors the setting when updating the internal domains list and when calculating prices. It does not yet remove cached prices.

**Comment by cascer1** [comment]
In the meantime, if you like the module, I'd appreciate your review on the [WHMCS marketplace](https://marketplace.whmcs.com/product/2786) :)
