### ISSUE TITLE
markup not being applied correctly

### ISSUE THREAD

**Issue by lcwsoft** [ducohosting/whmcs-enom-updater#26]
### Prerequisites

* [ ] Are you running the [latest version of the module](https://github.com/ducohosting/whmcs-enom-updater/wiki/Checking-for-updates)?
Yes
* [ ] Did you check the [debugging guide](https://github.com/ducohosting/whmcs-enom-updater/wiki/Debugging)?
Yes
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
Yes
* [ ] Did you [make sure a similar issue does not yet exist](https://github.com/ducohosting/whmcs-enom-updater/issues)?
Yes

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When USD is a secondary currency in your WHMCS installation and you've enabled marking up of the prices under Setup > Addon Modules, the resulting amount in USD is always less than expected.

For example: 1 year .com at 9.98 USD from eNom account and configured 50% markup

Should be: $14.97
.com 1 year USD gets set to 11.00

### Steps to Reproduce

1. Set up WHMCS
2. Edit default currency to CAD, and add USD as secondary under Setup > Payments > Currencies
3. Update exchange rates to ensure they are correct
4. Configure .com TLD under Setup > Products/Services > Domain Pricing with 1 year pricing of 1.00 for both currencies (just as placeholder)
5. Set up the addon with markup to 50%
6. run fetch and update operations
7. Check .com TLD pricing and note that USD is set to 11.00

**Expected behavior:** Given the settings USD pricing should be $14.97. Not $11.00

**Actual behavior:** USD pricing got set to $11.00

I suspect this is a bug in the pricing calculation. It should be applying the markup to the eNom returning pricing, and converting the resulting amount to the base currency in the install, then saving that to the TLD and term, and finally calling the WHMCS update pricing function to have it fill in the rest of the currencies and pricing simply and correctly.

### Versions

* WHMCS version: 7.1.2
* Module version: 2.1 alpha 2

**Comment by cascer1** [comment]
Thank you for reporting this bug. We are currently moving this repository to [GitLab](https://gitlab.com/ducohosting/whmcs-enom-updater). Could you please submit this issue there too?

**Comment by lcwsoft** [comment]
Was about to do this, but it appears you did it already: https://gitlab.com/ducohosting/whmcs-enom-updater/issues/28
