### ISSUE TITLE
fetch and calculate options give no success/failed messages

### ISSUE THREAD

**Issue by lcwsoft** [ducohosting/whmcs-enom-updater#27]
When you run either the fetch or update options under Addons > eNom domain pricing updater, the page just refreshes without any sort of notification at the top whether it has succeeded or failed like most other WHMCS addons (and WHMCS itself in fact).

This makes it harder to use and debug, as there is no way to know (besides checking the db) if it actually did anything. I'd suggest implementing notifications to solve that.

**Comment by cascer1** [comment]
[Issue migrated to GitLab](https://gitlab.com/ducohosting/whmcs-enom-updater/issues/27)
